//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSA_SQL.DB.SQL.Files
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashFlow
    {
        public int Id { get; set; }
        public long OperatingActivitiesCF { get; set; }
        public long Depreciation { get; set; }
        public long ReceivablesChange { get; set; }
        public long ObligationsStateChange { get; set; }
        public long ReserveAndOtherChange { get; set; }
        public long WorkingCapital { get; set; }
        public long InvestmentCF { get; set; }
        public long CapexIntangible { get; set; }
        public long FinancialCF { get; set; }
        public long SharesIssue { get; set; }
        public long LoansAndAdvancesObtained { get; set; }
        public long LoansAndAdvancesRepayed { get; set; }
        public long LiabilitiesChange { get; set; }
        public long Dividend { get; set; }
        public long TotalCF { get; set; }
    
        public virtual Reports Reports { get; set; }
    }
}
