//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSA_SQL.DB.SQL.Files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.Reports = new HashSet<Reports>();
        }
    
        public int Id { get; set; }
        public Nullable<decimal> Column_B { get; set; }
        public string Name { get; set; }
        public string Shortcut { get; set; }
        public Nullable<long> ShareNumbers { get; set; }
        public Nullable<decimal> SharePrice { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public string Column_I { get; set; }
        public Nullable<long> Column_J { get; set; }
        public Nullable<long> Column_K { get; set; }
        public Nullable<long> Column_L { get; set; }
        public string Href { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public string HeadAccount { get; set; }
        public string Profile { get; set; }
        public string Address { get; set; }
        public string HrefStatus { get; set; }
        public Nullable<long> VoteNumbers { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Column_W { get; set; }
        public Nullable<System.DateTime> Column_X { get; set; }
        public Nullable<long> Volumen20 { get; set; }
    
        public virtual ICollection<Reports> Reports { get; set; }
    }
}
