//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IDSA_SQL.DB.SQL.Files
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reports
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public short Quarter { get; set; }
        public System.DateTime FinancialStatmentDate { get; set; }
        public System.DateTime FinancialReportReleaseDate { get; set; }
    
        public virtual Balance Balance { get; set; }
        public virtual IncomeStatment IncomeStatment { get; set; }
        public virtual CashFlow CashFlow { get; set; }
        public virtual Company Company { get; set; }
    }
}
